spring:
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/books_management?characterEncoding=utf-8&useSSL=false&useUnicode=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    time-zone: Asia/Tokyo
  LOG_DIR: logs
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  #mapper-locations: com.ndb.booksManagementBack.mapper.*
